In [2]:
# 데이터 불러오기
import numpy as np
import pandas as pd

tmp_frm = pd.read_excel('samsung.xlsx')

In [3]:
# 서브셋 만들기
subset_frm = tmp_frm[['기준년월', '법정동명', '업종명_중분류', 'CNT']]

In [4]:
# 법정동명 리스트에 담기
lst = subset_frm['법정동명'].str.split()

# 통영시 데이터 인덱스 추출
idx_lst = []
for idx in range(len(lst)):
    if lst[idx][1] == '통영시':
        idx_lst.append(idx)
        
# 통영 데이터프레임 만들기
tongyeong_frm = subset_frm.iloc[idx_lst]
print(tongyeong_frm.head())

      기준년월        법정동명 업종명_중분류   CNT
2   202003  경남 통영시 영운리     음식점    83
6   202001  경남 통영시 삼화리  마트/할인점   118
9   202003  경남 통영시 덕포리     골프장    49
10  202002  경남 통영시 죽림리     편의점  4616
13  202002  경남 통영시 정량동    인테리어   193

In [5]:
# 인덱스 리셋
tongyeong_frm.reset_index(inplace=True)

In [6]:
# 드랍
tongyeong_frm.drop('index', axis=1, inplace = True)

C:\Users\ohans\AppData\Local\Temp\ipykernel_28292\3851835459.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tongyeong_frm.drop('index', axis=1, inplace = True)

In [7]:
# 시/동 구분
si_lst = []
dong_lst = []
for idx in range(len(tongyeong_frm['법정동명'].str.split())):
    si_lst.append(tongyeong_frm['법정동명'].str.split()[idx][1])
    dong_lst.append(tongyeong_frm['법정동명'].str.split()[idx][2])

In [8]:
tongyeong_frm['Si'] = si_lst
tongyeong_frm['Dong'] = dong_lst
tongyeong_frm

C:\Users\ohans\AppData\Local\Temp\ipykernel_28292\3964637651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tongyeong_frm['Si'] = si_lst
C:\Users\ohans\AppData\Local\Temp\ipykernel_28292\3964637651.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tongyeong_frm['Dong'] = dong_lst

        기준년월        법정동명 업종명_중분류   CNT   Si Dong
0     202003  경남 통영시 영운리     음식점    83  통영시  영운리
1     202001  경남 통영시 삼화리  마트/할인점   118  통영시  삼화리
2     202003  경남 통영시 덕포리     골프장    49  통영시  덕포리
3     202002  경남 통영시 죽림리     편의점  4616  통영시  죽림리
4     202002  경남 통영시 정량동    인테리어   193  통영시  정량동
...      ...         ...     ...   ...  ...  ...
2043  202101  경남 통영시 안정리      학원    13  통영시  안정리
2044  202103  경남 통영시 도남동    건강보조   130  통영시  도남동
2045  202002  경남 통영시 정량동    차량관리    37  통영시  정량동
2046  202001  경남 통영시 화삼리     음식점    60  통영시  화삼리
2047  202002  경남 통영시 안정리     편의점   366  통영시  안정리

[2048 rows x 6 columns]

In [9]:
tongyeong_frm.drop('법정동명', axis=1, inplace = True)

C:\Users\ohans\AppData\Local\Temp\ipykernel_28292\1708553547.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tongyeong_frm.drop('법정동명', axis=1, inplace = True)

In [10]:
tongyeong_frm

        기준년월 업종명_중분류   CNT   Si Dong
0     202003     음식점    83  통영시  영운리
1     202001  마트/할인점   118  통영시  삼화리
2     202003     골프장    49  통영시  덕포리
3     202002     편의점  4616  통영시  죽림리
4     202002    인테리어   193  통영시  정량동
...      ...     ...   ...  ...  ...
2043  202101      학원    13  통영시  안정리
2044  202103    건강보조   130  통영시  도남동
2045  202002    차량관리    37  통영시  정량동
2046  202001     음식점    60  통영시  화삼리
2047  202002     편의점   366  통영시  안정리

[2048 rows x 5 columns]

In [11]:
tongyeong_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop'}, inplace = True)

C:\Users\ohans\AppData\Local\Temp\ipykernel_28292\895068815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tongyeong_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop'}, inplace = True)

In [12]:
tongyeong_frm

        Date    Shop   CNT   Si Dong
0     202003     음식점    83  통영시  영운리
1     202001  마트/할인점   118  통영시  삼화리
2     202003     골프장    49  통영시  덕포리
3     202002     편의점  4616  통영시  죽림리
4     202002    인테리어   193  통영시  정량동
...      ...     ...   ...  ...  ...
2043  202101      학원    13  통영시  안정리
2044  202103    건강보조   130  통영시  도남동
2045  202002    차량관리    37  통영시  정량동
2046  202001     음식점    60  통영시  화삼리
2047  202002     편의점   366  통영시  안정리

[2048 rows x 5 columns]

In [13]:
tongyeong_frm.to_excel(tongyeong_data.frm.xlsx)

NameError: name 'tongyeong_data' is not defined