In [2]:
# 데이터 불러오기
import numpy as np
import pandas as pd

tmp_frm = pd.read_excel('./data/final_project/samsungcard/samsung.xlsx')

In [9]:
# 법정동명 리스트에 담기
lst = tmp_frm['법정동명'].str.split()

# 통영시 데이터 인덱스 추출
idx_lst = []
for idx in range(len(lst)):
    if lst[idx][1] == '통영시':
        idx_lst.append(idx)
        
# 통영 데이터프레임 만들기
tongyeong_frm = tmp_frm.iloc[idx_lst]
print(tongyeong_frm.head())

      기준년월       법정동코드        법정동명 업종코드_중분류 업종명_중분류   CNT  CNT_M_20_29  \
2   202003  4822025021  경남 통영시 영운리     DI02     음식점    83            0
6   202001  4822031024  경남 통영시 삼화리     SH02  마트/할인점   118            0
9   202003  4822034021  경남 통영시 덕포리     LE03     골프장    49            0
10  202002  4822034024  경남 통영시 죽림리     SH08     편의점  4616          390
13  202002  4822010900  경남 통영시 정량동     LI01    인테리어   193           10

    CNT_M_30_39  CNT_M_40_49  CNT_M_50_59  ...  CNT_TIME_A  CNT_TIME_B  \
2            15           10            0  ...           0           0
6            15           15           39  ...           0           0
9             0            0           22  ...           0           0
10         1204         1171          302  ...         386         290
13           30           25           49  ...           0           0

    CNT_TIME_C  CNT_TIME_D  CNT_TIME_E  CNT_TIME_F  CNT_TIME_G  CNT_TIME_H  \
2            0           0          25          27          14           0
6            0          15          14          20          30          20
9            0           0           0          12           0           0
10         353         364         464         458         495         716
13          25          43          29          52          31           0

    CNT_TIME_I  CNT_TIME_J
2            0           0
6           12           0
9            0           0
10         656         434
13           0           0

[5 rows x 35 columns]

In [10]:
gender_subset_frm = tongyeong_frm[['기준년월','법정동명','업종명_중분류','CNT','CNT_M_20_29','CNT_M_30_39','CNT_M_40_49',
                      'CNT_M_50_59','CNT_M_60','CNT_F_20_29','CNT_F_30_39','CNT_F_40_49','CNT_F_50_59',
                      'CNT_F_60']]
day_subset_frm = tongyeong_frm[['기준년월','법정동명','업종명_중분류','CNT','CNT_DAY_월','CNT_DAY_화','CNT_DAY_수','CNT_DAY_목','CNT_DAY_금',
                      'CNT_DAY_토','CNT_DAY_일','CNT_DAY_평일','CNT_DAY_주말공휴일']]

In [15]:
gender_subset_frm.reset_index(inplace=True, drop=True)

In [16]:
day_subset_frm.reset_index(inplace=True,drop=True)

In [18]:
gender_subset_frm['dong'] = gender_subset_frm['법정동명'].str.split(" ", expand = True)[2]
gender_subset_frm['si'] = gender_subset_frm['법정동명'].str.split(" ", expand = True)[1]
gender_subset_frm.drop('법정동명', axis=1, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_6488\904951579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gender_subset_frm['dong'] = gender_subset_frm['법정동명'].str.split(" ", expand = True)[2]
C:\Users\user\AppData\Local\Temp\ipykernel_6488\904951579.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gender_subset_frm['si'] = gender_subset_frm['법정동명'].str.split(" ", expand = True)[1]
C:\Users\user\AppData\Local\Temp\ipykernel_6488\904951579.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gender_subset_frm.drop('법정동명', axis=1, inplace=True)

In [20]:
gender_subset_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop', 'CNT':'cnt'}, inplace = True)

C:\Users\user\AppData\Local\Temp\ipykernel_6488\1335046888.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gender_subset_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop', 'CNT':'cnt'}, inplace = True)

In [21]:
gender_subset_frm

,Date,Shop,cnt,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,CNT_F_30_39,CNT_F_40_49,CNT_F_50_59,CNT_F_60,dong,si
0,202003,음식점,83,0,15,10,0,0,13,0,12,0,0,영운리,통영시
1,202001,마트/할인점,118,0,15,15,39,0,0,0,22,0,0,삼화리,통영시
2,202003,골프장,49,0,0,0,22,0,0,0,0,0,0,덕포리,통영시
3,202002,편의점,4616,390,1204,1171,302,154,269,425,404,175,122,죽림리,통영시
4,202002,인테리어,193,10,30,25,49,52,0,0,0,0,10,정량동,통영시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043,202101,학원,13,0,0,0,0,0,0,0,0,0,0,안정리,통영시
2044,202103,건강보조,130,0,0,16,18,21,0,10,15,14,16,도남동,통영시
2045,202002,차량관리,37,0,0,10,0,0,0,0,0,0,0,정량동,통영시
2046,202001,음식점,60,0,11,11,13,0,0,0,0,0,0,화삼리,통영시
2047,202002,편의점,366,0,92,116,57,0,11,33,16,14,15,안정리,통영시

In [22]:
day_subset_frm['dong'] = day_subset_frm['법정동명'].str.split(" ", expand = True)[2]
day_subset_frm['si'] = day_subset_frm['법정동명'].str.split(" ", expand = True)[1]
day_subset_frm.drop('법정동명', axis=1, inplace=True)
day_subset_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop', 'CNT':'cnt'}, inplace = True)
day_subset_frm

C:\Users\user\AppData\Local\Temp\ipykernel_6488\984075860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_subset_frm['dong'] = day_subset_frm['법정동명'].str.split(" ", expand = True)[2]
C:\Users\user\AppData\Local\Temp\ipykernel_6488\984075860.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_subset_frm['si'] = day_subset_frm['법정동명'].str.split(" ", expand = True)[1]
C:\Users\user\AppData\Local\Temp\ipykernel_6488\984075860.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_subset_frm.drop('법정동명', axis=1, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_6488\984075860.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day_subset_frm.rename(columns = {'기준년월' : 'Date', '업종명_중분류':'Shop', 'CNT':'cnt'}, inplace = True)

,Date,Shop,cnt,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일,dong,si
0,202003,음식점,83,10,13,0,0,0,26,20,37,46,영운리,통영시
1,202001,마트/할인점,118,17,0,17,25,21,18,13,73,45,삼화리,통영시
2,202003,골프장,49,0,0,0,0,0,0,10,30,19,덕포리,통영시
3,202002,편의점,4616,584,637,546,671,669,839,670,3107,1509,죽림리,통영시
4,202002,인테리어,193,38,33,31,27,29,29,0,158,35,정량동,통영시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043,202101,학원,13,0,0,0,0,0,0,0,13,0,안정리,통영시
2044,202103,건강보조,130,30,29,16,17,21,17,0,111,19,도남동,통영시
2045,202002,차량관리,37,0,0,0,0,0,0,0,29,0,정량동,통영시
2046,202001,음식점,60,11,0,11,0,0,13,0,31,29,화삼리,통영시
2047,202002,편의점,366,59,46,38,52,58,55,58,253,113,안정리,통영시

In [25]:
gender_subset_frm.groupby('Shop').sum()

,Date,cnt,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,CNT_F_30_39,CNT_F_40_49,CNT_F_50_59,CNT_F_60
Shop,,,,,,,,,,,,
가례,1212312,109,0,0,0,0,0,0,0,0,11,0
가전,4243040,3328,67,387,585,460,303,26,199,442,336,169
건강보조,18184680,27846,418,2891,4479,3056,3163,784,2939,3313,2781,2377
골프장,4041040,841,0,44,174,196,0,0,0,45,29,10
공과금,1010310,82,0,0,0,0,0,0,0,0,0,0
관람,2222522,920,12,103,229,63,16,54,81,104,45,0
교육기타,2424624,236,0,0,0,0,0,0,0,24,0,0
교통,404205,119,0,0,28,15,17,0,0,0,0,0
놀이공원,1212312,773,0,114,166,135,78,10,25,41,43,10
동물병원,5253352,2493,99,240,323,197,68,210,203,286,206,77
마트/할인점,44047533,155531,3857,18669,27108,18462,11296,4824,16677,23002,17705,10837
문구사무용품,4041040,1719,12,230,311,88,50,23,272,285,81,33
병원,16972368,31481,405,2963,4986,3715,3821,626,3022,3730,3780,3110
보험,1212312,132,0,0,10,0,0,0,0,0,0,0
뷰티,15558153,6596,250,779,1104,527,103,165,432,763,523,233
서적,3232832,1715,0,93,416,113,0,10,212,437,72,10
숙박,15154156,7641,198,873,1564,1269,382,116,398,683,439,144
스포츠시설,4849247,1012,76,76,169,64,0,16,11,101,13,10
스포츠의류용품,8081977,2902,0,227,375,280,133,12,70,285,388,319
유아교육,1616416,557,0,207,95,0,0,0,109,35,0,0
유흥,7879782,3959,268,583,962,820,216,100,63,157,51,11
음식점,46471965,156503,7469,22391,33064,21873,9186,6919,14174,20037,12086,5463
의류,9294393,3673,0,136,291,105,27,87,345,669,595,343
인테리어,22225827,6396,10,413,901,1027,709,0,111,342,323,264
제과점,12527123,15485,244,1835,2505,1273,441,775,2197,3022,1498,500
주생활관리,15558058,5058,46,291,573,468,186,53,756,897,270,90
주유,24043937,53660,1758,7627,12195,9144,5636,885,3411,5051,4293,2091
주차,3031230,721,11,93,97,60,12,0,44,33,29,0
차량관리,11921115,4088,22,396,777,644,403,0,170,253,213,87
취미,20407503,13314,1870,2014,2834,1641,718,428,481,717,621,251
커피/음료,30106500,25741,1381,3516,3896,1515,466,2286,3672,3657,1689,426
패션잡화,13941938,14986,219,1350,2004,1692,1087,432,1138,2072,2057,1536
편의점,28287382,112977,10381,23760,26526,11559,4086,5936,9593,11438,5809,2452
학원,6870064,1737,0,99,419,54,0,0,188,462,0,0
화장품,6263462,3683,119,219,282,230,0,503,493,655,457,172