#### 파이썬에서 엑셀 가져오기
-(삼성카드)가맹점 기반 지역별 소비행태.xlsx 파일 불러오기  
-군산시에 관한 자료  
-기준년월 = Date, 법정동명 = area, 업종명_중뷴류 = Shop으로 컬럼명 변경  
-군산시 / 개복동 의 형태로 제작
-엑셀의 A : Y 행 사용. 단 B와 D열 제거

In [1]:
import pandas as pd

In [2]:
#gs = 군산
#엑셀의 A ~ Y행까지 추출
gs_df = pd.read_excel('C:/Users/ohans/Desktop/multicampus/big data/class/project/final project/data/(삼성카드)가맹점 기반 지역별 소비행태.xlsx',
                     usecols = 'A:Y')

In [3]:
gs_df

,기준년월,법정동코드,법정동명,업종코드_중분류,업종명_중분류,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,...,CNT_F_60,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일
0,202003,4611013700,전남 목포시 중앙동2가,DI02,음식점,79,0,14,19,14,...,0,0,11,0,10,0,18,19,42,37
1,202001,4513013500,전북 군산시 경장동,LE01,취미,70,11,17,32,0,...,0,14,0,0,0,11,16,13,33,37
2,202003,4822025021,경남 통영시 영운리,DI02,음식점,83,0,15,10,0,...,0,10,13,0,0,0,26,20,37,46
3,202003,4513013400,전북 군산시 조촌동,SH10,아울렛,3643,205,589,434,216,...,165,296,380,302,320,378,862,1105,1676,1967
4,202101,4513013400,전북 군산시 조촌동,ED07,서적,17,0,0,0,0,...,0,0,0,0,0,0,0,0,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7685,202002,4611010200,전남 목포시 산정동,DI01,커피/음료,1444,139,207,214,115,...,46,182,176,184,175,222,281,224,939,505
7686,202103,4513037024,전북 군산시 도암리,SH08,편의점,110,10,18,18,17,...,0,19,26,15,17,15,0,0,91,19
7687,202002,4822010900,경남 통영시 정량동,DR04,차량관리,37,0,0,10,0,...,0,0,0,0,0,0,0,0,29,0
7688,202001,4822031021,경남 통영시 화삼리,DI02,음식점,60,0,11,11,13,...,0,11,0,11,0,0,13,0,31,29
7689,202002,4822034027,경남 통영시 안정리,SH08,편의점,366,0,92,116,57,...,15,59,46,38,52,58,55,58,253,113

원하는 자료만 추출

In [4]:
#B, D열 제거
gs_df2 = gs_df.drop(['법정동코드','업종코드_중분류'],axis=1)

In [5]:
gs_df2.head()

,기준년월,법정동명,업종명_중분류,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,...,CNT_F_60,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일
0,202003,전남 목포시 중앙동2가,음식점,79,0,14,19,14,0,0,...,0,0,11,0,10,0,18,19,42,37
1,202001,전북 군산시 경장동,취미,70,11,17,32,0,0,0,...,0,14,0,0,0,11,16,13,33,37
2,202003,경남 통영시 영운리,음식점,83,0,15,10,0,0,13,...,0,10,13,0,0,0,26,20,37,46
3,202003,전북 군산시 조촌동,아울렛,3643,205,589,434,216,119,422,...,165,296,380,302,320,378,862,1105,1676,1967
4,202101,전북 군산시 조촌동,서적,17,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,11,0

In [6]:
#컬럼명 변경
gs_df3 = gs_df2.rename(columns={'기준년월' :'Date',
                                '법정동명' :'area',
                                 '업종명_중분류' :'Shop'})

In [7]:
gs_df3.head()

,Date,area,Shop,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,...,CNT_F_60,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일
0,202003,전남 목포시 중앙동2가,음식점,79,0,14,19,14,0,0,...,0,0,11,0,10,0,18,19,42,37
1,202001,전북 군산시 경장동,취미,70,11,17,32,0,0,0,...,0,14,0,0,0,11,16,13,33,37
2,202003,경남 통영시 영운리,음식점,83,0,15,10,0,0,13,...,0,10,13,0,0,0,26,20,37,46
3,202003,전북 군산시 조촌동,아울렛,3643,205,589,434,216,119,422,...,165,296,380,302,320,378,862,1105,1676,1967
4,202101,전북 군산시 조촌동,서적,17,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,11,0

In [8]:
#군산시 추출
gs_df4 = gs_df3[gs_df3['area'].str.contains('군산시', na = False)]

In [9]:
gs_df4

,Date,area,Shop,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,...,CNT_F_60,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일
1,202001,전북 군산시 경장동,취미,70,11,17,32,0,0,0,...,0,14,0,0,0,11,16,13,33,37
3,202003,전북 군산시 조촌동,아울렛,3643,205,589,434,216,119,422,...,165,296,380,302,320,378,862,1105,1676,1967
4,202101,전북 군산시 조촌동,서적,17,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,11,0
5,202101,전북 군산시 문화동,마트/할인점,389,26,37,94,53,31,15,...,15,52,34,53,51,66,64,69,238,151
7,202101,전북 군산시 경암동,차량관리,42,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,30,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7681,202003,전북 군산시 나운동,관람,49,10,0,0,0,0,0,...,0,0,0,0,0,0,12,17,20,29
7682,202101,전북 군산시 미룡동,문구사무용품,45,0,0,13,0,0,0,...,0,0,0,11,0,0,0,0,33,12
7683,202102,전북 군산시 문화동,의류,11,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7684,202101,전북 군산시 지경리,음식점,157,10,15,25,44,11,0,...,0,19,16,11,23,30,32,26,92,65
7686,202103,전북 군산시 도암리,편의점,110,10,18,18,17,0,0,...,0,19,26,15,17,15,0,0,91,19

In [10]:
#중복되는 '전북' 제거
gs_df4['area']=gs_df4['area'].str.replace('전북 ','')

C:\Users\ohans\AppData\Local\Temp\ipykernel_14496\2875225219.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gs_df4['area']=gs_df4['area'].str.replace('전북 ','')

In [11]:
gs_df4.head()

,Date,area,Shop,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,...,CNT_F_60,CNT_DAY_월,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일
1,202001,군산시 경장동,취미,70,11,17,32,0,0,0,...,0,14,0,0,0,11,16,13,33,37
3,202003,군산시 조촌동,아울렛,3643,205,589,434,216,119,422,...,165,296,380,302,320,378,862,1105,1676,1967
4,202101,군산시 조촌동,서적,17,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,11,0
5,202101,군산시 문화동,마트/할인점,389,26,37,94,53,31,15,...,15,52,34,53,51,66,64,69,238,151
7,202101,군산시 경암동,차량관리,42,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,30,12

In [12]:
#area의 군산시와 지역명을 분리
#expand = True를 할 경우 split값이 바로 데이터프레임으로 추출
gs_area = gs_df4['area'].str.split(' ',expand = True)

In [13]:
gs_area.head()

     0    1
1  군산시  경장동
3  군산시  조촌동
4  군산시  조촌동
5  군산시  문화동
7  군산시  경암동

In [14]:
gs_area.columns =['Si','Dong']

In [15]:
gs_area

       Si Dong
1     군산시  경장동
3     군산시  조촌동
4     군산시  조촌동
5     군산시  문화동
7     군산시  경암동
...   ...  ...
7681  군산시  나운동
7682  군산시  미룡동
7683  군산시  문화동
7684  군산시  지경리
7686  군산시  도암리

[3551 rows x 2 columns]

In [16]:
#분리한 SI, Dong컬럼을 원 컬럼과 결합
gs_df5 = pd.concat([gs_df4, gs_area], axis = 1)

In [17]:
gs_df5.head()

,Date,area,Shop,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,...,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일,Si,Dong
1,202001,군산시 경장동,취미,70,11,17,32,0,0,0,...,0,0,0,11,16,13,33,37,군산시,경장동
3,202003,군산시 조촌동,아울렛,3643,205,589,434,216,119,422,...,380,302,320,378,862,1105,1676,1967,군산시,조촌동
4,202101,군산시 조촌동,서적,17,0,0,0,0,0,0,...,0,0,0,0,0,0,11,0,군산시,조촌동
5,202101,군산시 문화동,마트/할인점,389,26,37,94,53,31,15,...,34,53,51,66,64,69,238,151,군산시,문화동
7,202101,군산시 경암동,차량관리,42,0,0,0,0,0,0,...,0,0,0,0,0,0,30,12,군산시,경암동

In [18]:
#area 컬럼 제거
gs_df6 = gs_df5.drop(['area'],axis=1)

In [19]:
gs_df6.head()

,Date,Shop,CNT,CNT_M_20_29,CNT_M_30_39,CNT_M_40_49,CNT_M_50_59,CNT_M_60,CNT_F_20_29,CNT_F_30_39,...,CNT_DAY_화,CNT_DAY_수,CNT_DAY_목,CNT_DAY_금,CNT_DAY_토,CNT_DAY_일,CNT_DAY_평일,CNT_DAY_주말공휴일,Si,Dong
1,202001,취미,70,11,17,32,0,0,0,0,...,0,0,0,11,16,13,33,37,군산시,경장동
3,202003,아울렛,3643,205,589,434,216,119,422,590,...,380,302,320,378,862,1105,1676,1967,군산시,조촌동
4,202101,서적,17,0,0,0,0,0,0,0,...,0,0,0,0,0,0,11,0,군산시,조촌동
5,202101,마트/할인점,389,26,37,94,53,31,15,47,...,34,53,51,66,64,69,238,151,군산시,문화동
7,202101,차량관리,42,0,0,0,0,0,0,0,...,0,0,0,0,0,0,30,12,군산시,경암동

In [20]:
#Si와 Dong 멀티인덱스
gs_df7 = gs_df6.set_index(["Si","Dong"])

In [21]:
gs_df7.head()

            Date    Shop   CNT  CNT_M_20_29  CNT_M_30_39  CNT_M_40_49  \
Si  Dong
군산시 경장동   202001      취미    70           11           17           32
    조촌동   202003     아울렛  3643          205          589          434
    조촌동   202101      서적    17            0            0            0
    문화동   202101  마트/할인점   389           26           37           94
    경암동   202101    차량관리    42            0            0            0

          CNT_M_50_59  CNT_M_60  CNT_F_20_29  CNT_F_30_39  ...  CNT_F_60  \
Si  Dong                                                   ...
군산시 경장동             0         0            0            0  ...         0
    조촌동           216       119          422          590  ...       165
    조촌동             0         0            0            0  ...         0
    문화동            53        31           15           47  ...        15
    경암동             0         0            0            0  ...         0

          CNT_DAY_월  CNT_DAY_화  CNT_DAY_수  CNT_DAY_목  CNT_DAY_금  CNT_DAY_토  \
Si  Dong
군산시 경장동          14          0          0          0         11         16
    조촌동         296        380        302        320        378        862
    조촌동           0          0          0          0          0          0
    문화동          52         34         53         51         66         64
    경암동           0          0          0          0          0          0

          CNT_DAY_일  CNT_DAY_평일  CNT_DAY_주말공휴일
Si  Dong
군산시 경장동          13          33             37
    조촌동        1105        1676           1967
    조촌동           0          11              0
    문화동          69         238            151
    경암동           0          30             12

[5 rows x 22 columns]

In [24]:
#보기 좋게 Dong별로 분류
gs_df8 = gs_df7.sort_values('Dong', ascending = True)

In [25]:
gs_df8.head()

            Date Shop  CNT  CNT_M_20_29  CNT_M_30_39  CNT_M_40_49  \
Si  Dong
군산시 개복동   202102  음식점   17            0            0            0
    개복동   202101  음식점   21            0            0            0
    개복동   202003  음식점   19            0            0            0
    개복동   202001  음식점   30            0            0            0
    개복동   202103  음식점   18            0            0            0

          CNT_M_50_59  CNT_M_60  CNT_F_20_29  CNT_F_30_39  ...  CNT_F_60  \
Si  Dong                                                   ...
군산시 개복동             0         0            0            0  ...         0
    개복동             0         0            0            0  ...         0
    개복동             0         0            0            0  ...         0
    개복동             0         0            0            0  ...         0
    개복동             0         0            0            0  ...         0

          CNT_DAY_월  CNT_DAY_화  CNT_DAY_수  CNT_DAY_목  CNT_DAY_금  CNT_DAY_토  \
Si  Dong
군산시 개복동           0          0          0          0          0          0
    개복동           0          0          0          0          0          0
    개복동           0          0          0          0          0          0
    개복동           0          0          0          0          0          0
    개복동           0          0          0          0          0          0

          CNT_DAY_일  CNT_DAY_평일  CNT_DAY_주말공휴일
Si  Dong
군산시 개복동           0          14              0
    개복동           0          15              0
    개복동           0          11              0
    개복동           0          15             15
    개복동           0          11              0

[5 rows x 22 columns]

In [26]:
#엑셀로 저장
#gs_df8.to_excel('Gunsan.xlsx')